//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionRule
    {
        public int RuleID { get; set; }
        public string RuleName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
